### ISSUE TITLE
Reorganize Cilium Docker files

### ISSUE THREAD

**Issue by ysksuzuki** [cybozu/neco-containers#1008]
## What

Currently, we build bpftool, envoy and iproutes and copy them to the cilium image directly, not building builder and runtime images. This divergent structure makes our regular container maintenance very hard.

## How

Reorganize Cilium Dockerfiles in neco-containers and follow the upstream structure

## Checklist

- [ ] Finish implentation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by yokaze** [comment]
Moved to another tracking system
